version: "3"
services:
    loadbalancer:
        build:
            dockerfile: loadbalancer.dockerfile
            context: .
        ports: 
            - "8081:80"
        container_name: loadbalancer
        networks:
            - supernet
        depends_on: 
            - node1
            - node2
            - node3        
    node1:
        image: jmcarbo/nginx-php-fpm
        container_name: node1
        volumes: 
            - ./index.php:/usr/share/nginx/html/index.php
            - ./bootstrap.min.css:/usr/share/nginx/html/bootstrap.min.css
        networks:
            - supernet        
    node2:
        image: jmcarbo/nginx-php-fpm
        container_name: node2
        volumes: 
            - ./index.php:/usr/share/nginx/html/index.php
            - ./bootstrap.min.css:/usr/share/nginx/html/bootstrap.min.css
        networks:
            - supernet        
    node3:
        image: jmcarbo/nginx-php-fpm
        container_name: node3
        volumes: 
            - ./index.php:/usr/share/nginx/html/index.php
            - ./bootstrap.min.css:/usr/share/nginx/html/bootstrap.min.css
        networks:
            - supernet        
            
networks: 
    supernet:
        driver: bridge